
// HIER MUESSEN DIE NAMEN DER NETZE DEFINIERT WERDEN

#define DURNETNAME "dauernet"
#define INTNETNAME "intonet"

// HIER MUESSEN DIE NETZHEADERDATEIEN EINGEBUNDEN WERDEN
// IN DEN HEADER-DATEIEN MUSS NACH extern EIN "C" EINGEFUEGT WERDEN
// DIE ZUGEHOERIGEN .c-DATEIEN MUESSEN DAZUGELINKT WERDEN

// BEIM DAUERNETZ WIRD FUER ALLE SILBEN DIE SILBENDAUER ALS
// AUSGABEPARAMETER ERWARTET

// BEIM INTONATIONSNETZ WERDEN FUER ALLE BETONTEN SILBEN DIE
// PARAMETER delay amplitude betali betare IN DIESER REIHENFOLGE
// ERWARTET

#include "dauernet.h"
#include "intonet.h"

// HIER MUESSEN DIE NAMEN DER PARAMETERDATEIEN FESTGELEGT WERDEN,
// DIE DIE EIN- UND AUSGABEPARAMETER MIT IHREM RANGE FESTLEGEN


const char* DURNETPARNAME = "dauer.par" ;
const char* INTNETPARNAME = "into.par" ;
